---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pvc-cbf
  namespace: flux-services
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: ska-mid-helmreleases
  path: ./datacentres/mid-aa/carel-se-berg/deployment/pvc-cbf
  prune: true
  wait: false
  timeout: 1m0s