---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ska007-dish-lmc
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ska-mid-itf-dish-lmc
      sourceRef:
        kind: HelmRepository
        name: skatelescope
        namespace: flux-system
      version: 23.2.1
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 1h0m0s
  kubeConfig:
    secretRef:
      key: value.yaml
      name: ska007-cluster-config
  releaseName: ska007-dish-lmc
  storageNamespace: ska007-dish-lmc
  targetNamespace: ska007-dish-lmc
  timeout: 15m
  upgrade:
    remediation:
      retries: 5
  valuesFrom:
  - kind: Secret
    name: vault-shared
    optional: true
    valuesKey: values.yaml
  - kind: Secret
    name: vault-mid-itf-shared
    optional: true
    valuesKey: values.yaml
  - kind: Secret
    name: vault-mid-itf-ska007-ska-mid-itf-dish-lmc
    valuesKey: values.yaml
  - kind: Secret
    name: vault-mid-itf-ska007-ska-mid-itf-dish-lmc
    valuesKey: ska-taranta.enabled
    targetPath: ska-taranta.enabled
