---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ska036-archiver
  namespace: flux-services
spec:
  storageNamespace: dish-lmc-ska036
  targetNamespace: dish-lmc-ska036
  releaseName: ska036-archiver
  kubeConfig:
    secretRef:
      key: values.yml
      name: vault-miditf-ska036-kubeconfig
  valuesFrom:
    - kind: Secret
      name: vault-shared-ska-tango-archiver
      valuesKey: values.yml
    - kind: Secret
      name: vault-miditf-dish-ska036-archiver
      valuesKey: values.yml
    # - kind: Secret
    #   name: vault-eda-credentials
    #   valuesKey: login
    #   targetPath: archviewer.instances[0].timescale_login
    # - kind: Secret
    #   name: vault-eda-credentials
    #   valuesKey: dbpassword
    #   targetPath: dbpassword
