---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: skatelescope
  namespace: flux-system
spec:
  interval: 30m
  url: https://artefact.skao.int/repository/helm-internal