---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: central-controller
  namespace: flux-services
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: ska-mid-itf-sut
      version: "25.6.3"
      sourceRef:
        kind: HelmRepository
        name: skatelescope
  releaseName: milestoneXXX-facilityXXX
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      strategy: "uninstall"
      retries: 3
  storageNamespace: ska-mid-itf-sut
  targetNamespace: ska-mid-itf-sut
  valuesFrom:
    - kind: Secret
      name: vault-shared-sut
      valuesKey: values.yml
    - kind: Secret
      name: vault-shared-mid-cbf
      valuesKey: values.yml
    - kind: Secret
      name: vault-shared-mid-csp
    - kind: Secret
      name: vault-shared-mid-global
      valuesKey: values.yml
    - kind: Secret
      name: vault-shared-mid-sdp
      valuesKey: values.yml
    - kind: Secret
      name: vault-shared-mid-tango
      valuesKey: values.yml
    - kind: Secret
      name: vault-shared-mid-tmc
      valuesKey: values.yml
    - kind: Secret
      name: vault-shared-mid-utils
      valuesKey: values.yml
