---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-shared-sut
  namespace: flux-services
spec:
  type: kv-v2
  mount: shared
  path: global/ska-sut
  # version: 3
  destination:
    name: vault-shared-sut
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-shared-cbf
  namespace: flux-services
spec:
  type: kv-v2
  mount: shared
  path: global/ska-umbrella-cbf
  # version: 3
  destination:
    name: vault-shared-cbf
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-shared-global
  namespace: flux-services
spec:
  type: kv-v2
  mount: shared
  path: global/ska-umbrella-global
  # version: 3
  destination:
    name: vault-shared-global
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-shared-sdp
  namespace: flux-services
spec:
  type: kv-v2
  mount: shared
  path: global/ska-umbrella-sdp
  # version: 3
  destination:
    name: vault-shared-sdp
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-shared-tango
  namespace: flux-services
spec:
  type: kv-v2
  mount: shared
  path: global/ska-umbrella-tango
  # version: 3
  destination:
    name: vault-shared-tango
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-shared-tmc
  namespace: flux-services
spec:
  type: kv-v2
  mount: shared
  path: global/ska-umbrella-tmc
  # version: 3
  destination:
    name: vault-shared-tmc
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-shared-utils
  namespace: flux-services
spec:
  type: kv-v2
  mount: shared
  path: global/ska-umbrella-utils
  # version: 3
  destination:
    name: vault-shared-utils
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth