---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-shared-sut
  namespace: flux-services
spec:
  type: kv-v2
  mount: shared
  path: global/ska-sut
  # version: 3
  destination:
    name: vault-shared-sut
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-shared-mid-cbf
  namespace: flux-services
spec:
  type: kv-v2
  mount: shared
  path: global/ska-mid/cbf
  # version: 3
  destination:
    name: vault-shared-mid-cbf
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-shared-mid-csp
  namespace: flux-services
spec:
  type: kv-v2
  mount: shared
  path: global/ska-mid/csp
  # version: 3
  destination:
    name: vault-shared-mid-csp
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-shared-mid-global
  namespace: flux-services
spec:
  type: kv-v2
  mount: shared
  path: global/ska-mid/global
  # version: 3
  destination:
    name: vault-shared-mid-global
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-shared-mid-sdp
  namespace: flux-services
spec:
  type: kv-v2
  mount: shared
  path: global/ska-mid/sdp
  # version: 3
  destination:
    name: vault-shared-mid-sdp
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-shared-mid-tango
  namespace: flux-services
spec:
  type: kv-v2
  mount: shared
  path: global/ska-mid/tango
  # version: 3
  destination:
    name: vault-shared-mid-tango
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-shared-mid-tmc
  namespace: flux-services
spec:
  type: kv-v2
  mount: shared
  path: global/ska-mid/tmc
  # version: 3
  destination:
    name: vault-shared-mid-tmc
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-shared-mid-utils
  namespace: flux-services
spec:
  type: kv-v2
  mount: shared
  path: global/ska-mid/utils
  # version: 3
  destination:
    name: vault-shared-mid-utils
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth