---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-shared-sut
  namespace: flux-services
spec:
  type: kv-v2
  mount: shared
  path: global/ska-sut
  # version: 3
  destination:
    name: vault-shared-sut
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
