---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pvc-cbf-ec
  namespace: flux-services
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: ska-mid-helmreleases
  path: ./datacentres/mid-aa/losberg/deployment/pvc-cbf-ec
  prune: true
  wait: false
  timeout: 1m0s
  dependsOn:
    - name: namespaces-ska-mid
      namespace: flux-services