apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flux-central-controller-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: ceph-cephfs
  volumeMode: Filesystem
