---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth-skao-int
  namespace: flux-system
spec:
  method: kubernetes
  mount: mid-itf
  kubernetes:
    role: kube-role
    serviceAccount: default
    audiences:
      - vault

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-shared
  namespace: flux-system
spec:
  type: kv-v2
  mount: shared
  path: default
  destination:
    name: vault-shared
    create: true
  refreshAfter: 1800s
  vaultAuthRef: static-auth-skao-int

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-mid-itf-shared
  namespace: flux-system
spec:
  type: kv-v2
  mount: mid-itf
  path: shared/default
  destination:
    name: vault-mid-itf-shared
    create: true
  refreshAfter: 1800s
  vaultAuthRef: static-auth-skao-int

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-mid-itf-ska007-ska-mid-itf-dish-lmc
  namespace: flux-system
spec:
  type: kv-v2
  mount: mid-itf
  path: ska007/ska-mid-itf-dish-lmc
  version: 1
  destination:
    name: vault-mid-itf-ska007-ska-mid-itf-dish-lmc
    create: true
  refreshAfter: 1800s
  vaultAuthRef: static-auth-skao-int
