---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../shared/deployment/sdp-pvc

patches:
  - target:
      kind: PersistentVolumeClaim
      name: flux-central-controller-pvc
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: shared-ska-dataproducts
