---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../shared/deployment/pvc

patches:
  - target:
      kind: PersistentVolumeClaim
      name: pvc
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: staging-pvc
