---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: skaxxx-archiver
  namespace: flux-services
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: ska-tango-archiver
      version: '2.8.1'
      sourceRef:
        kind: HelmRepository
        name: skatelescope
  releaseName: system-aiv # This can be either `system-aiv` or `dish-aiv`. Default value set to `system-aiv` on group level, and overwritten on dish level.
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  storageNamespace: ska-mid-itf-dish-lmc-skaxxx
  targetNamespace: ska-mid-itf-dish-lmc-skaxxx
  valuesFrom:
  - kind: Secret
    name: vault-shared-ska-tango-archiver
    valuesKey: values.yml
      