---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-shared-ska-tango-archiver
  namespace: flux-services
spec:
  type: kv-v2
  mount: shared
  path: global/ska-tango-archiver
  # version: 3
  destination:
    name: vault-shared-ska-tango-archiver
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
