---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ska063-dish
  namespace: flux-services
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: ska-mid-helmreleases
  path: ./datacentres/mid-aa/ska063/deployment/dish
  prune: true
  wait: false
  timeout: 1m0s
