---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ska063-dish
  namespace: flux-services
spec:
  storageNamespace: dish-lmc-ska063
  targetNamespace: dish-lmc-ska063
  releaseName: ska-mid-itf-dish-ska063
  kubeConfig:
    secretRef:
      key: values.yml
      name: vault-midaa-ska063-kubeconfig
  valuesFrom:
    - kind: Secret
      name: vault-shared-dish
      valuesKey: values.yml
    - kind: Secret
      name: vault-midaa-dish-ska063
      valuesKey: values.yml
    - kind: Secret
      name: vault-car-publisher
      valuesKey: publisher_password
      targetPath: global.raw_user_pass
