---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ska063-dish
  namespace: flux-services
spec:
  interval: 1m0s
  storageNamespace: dish-lmc-ska063
  targetNamespace: dish-lmc-ska063
  releaseName: mid-aiv-dish-ska063
  valuesFrom:
    - kind: Secret
      name: vault-midaa-dish-ska418-no-hw
      valuesKey: values.yml
