---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ska100-dish
  namespace: flux-services
spec:
  storageNamespace: dish-lmc-ska100
  targetNamespace: dish-lmc-ska100
  releaseName: dishaiv-miditf # this should remain commented unless we realise we need a separation on per-dish releases.
  kubeConfig:
    secretRef:
      key: values.yml
      name: vault-miditf-ska100-kubeconfig
  valuesFrom:
    - kind: Secret
      name: vault-shared-dish
      valuesKey: values.yml
    - kind: Secret
      name: vault-miditf-dish-ska100
      valuesKey: values.yml
    - kind: Secret
      name: vault-car-publisher
      valuesKey: publisher_password
      targetPath: global.raw_user_pass
    - kind: Secret
      name: vault-miditf-ska100-kubeconfig
      valuesKey: values.yml