---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ska036-dish
  namespace: flux-services
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: ska-mid-itf
  path: ./datacentres/mid-itf/ska036/deployment/dish
  prune: true
  wait: true
  timeout: 5m0s
