---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ska036-dish
  namespace: flux-services
spec:
  storageNamespace: dish-lmc-ska036
  targetNamespace: dish-lmc-ska036
  releaseName: mid-aiv-dish-ska036 # this should remain commented unless we realise we need a separation on per-dish releases.
  interval: 1m0s
  kubeConfig:
    secretRef:
      key: values.yml
      name: vault-miditf-ska036-kubeconfig
  valuesFrom:
    - kind: Secret
      name: vault-shared-dish
      valuesKey: values.yml
    - kind: Secret
      name: vault-miditf-dish-ska036
      valuesKey: values.yml
    - kind: Secret
      name: vault-miditf-dish-ska036-no-hw
      valuesKey: values.yml