---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-miditf-dish-ska036
  namespace: flux-services
spec:
  type: kv-v2
  mount: mid-itf
  path: ska036/ska-dish-lmc
  # version: 6
  destination:
    name: vault-miditf-dish-ska036
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-miditf-dish-ska036-no-hw
  namespace: flux-services
spec:
  type: kv-v2
  mount: mid-itf
  path: ska036/ska-dish-lmc-no-hw
  # version: 2
  destination:
    name: vault-miditf-dish-ska036-no-hw
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-miditf-ska036-kubeconfig
  namespace: flux-services
spec:
  type: kv-v2
  mount: mid-itf
  path: ska036/kubeconfig
  # version: 6
  destination:
    name: vault-miditf-ska036-kubeconfig
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
