---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: central-controller
  namespace: flux-services
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: ska-mid-itf
  path: ./datacentres/mid-aa/karel-se-berg/deployment/central-controller
  prune: true
  wait: false
  timeout: 1m0s
