---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - central-controller/fluxtrigger.yml
  - namespaces/fluxtrigger.yml
  - pvc-cbf-ec/fluxtrigger.yml
  # - pvc-dpd/fluxtrigger.yml
  - data-product-dashboard/fluxtrigger.yml
  - dish/fluxtrigger.yml
