---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dataproducts-namespace
  namespace: flux-services
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: ska-mid-helmreleases
  path: ./datacentres/mid-itf/central-controller/deployment/dataproducts-namespace
  prune: true
  wait: false
  timeout: 1m0s