---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../shared/deployment/sdp-namespace

patches:
  - target:
      kind: Namespace
      name: sdp-namespace
    patch: |-
      - op: replace
        path: /metadata/name
        value: flux-central-controller-sdp
