---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-midaa-dish-ska063-archiver
  namespace: flux-services
spec:
  type: kv-v2
  mount: mid-aa
  path: ska063/ska-tango-archiver
  # version: 3
  destination:
    name: vault-midaa-dish-ska063-archiver
    create: true
  refreshAfter: 30s
  vaultAuthRef: flux-vault-auth
