---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ska001-dish
  namespace: flux-services
spec:
  interval: 1m0s
  storageNamespace: dish-lmc-ska001
  targetNamespace: dish-lmc-ska001
  releaseName: mid-aiv-dish-ska001
  kubeConfig:
    secretRef:
      key: values.yml
      name: vault-midaa-ska001-kubeconfig
  valuesFrom:
    - kind: Secret
      name: vault-midaa-dish-ska001
      valuesKey: values.yml
    - kind: Secret
      name: vault-midaa-dish-ska001-no-hw
      valuesKey: values.yml
