---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-midaa-dish-ska001
  namespace: flux-services
spec:
  type: kv-v2
  mount: mid-aa
  path: ska001/ska-dish-lmc
  # version: 2
  destination:
    name: vault-midaa-dish-ska001
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-midaa-dish-ska001-no-hw
  namespace: flux-services
spec:
  type: kv-v2
  mount: mid-aa
  path: ska001/ska-dish-lmc-no-hw
  # version: 2
  destination:
    name: vault-midaa-dish-ska001-no-hw
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-midaa-ska001-kubeconfig
  namespace: flux-services
spec:
  type: kv-v2
  mount: mid-aa
  path: ska001/kubeconfig
  # version: 2
  destination:
    name: vault-midaa-ska001-kubeconfig
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth