---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: central-controller
  namespace: flux-services
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: ska-mid-helmreleases
  path: ./datacentres/mid-aa/carel-se-berg/deployment/central-controller
  prune: true
  wait: false
  timeout: 1m0s
  dependsOn:
    - name: namespaces
      namespace: flux-services
    - name: pvc-sdp
      namespace: flux-services
    - name: pvc-cbf
      namespace: flux-services