---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: central-controller
  namespace: flux-services
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: ska-mid-helmreleases
  path: ./datacentres/mid-itf/central-controller/deployment/system-under-test
  prune: true
  wait: false
  timeout: 1m0s
  dependsOn: 
    - name: sdp-pvc
      namespace: flux-services
    - name: sdp-namespace
      namespace: flux-services
    - name: dataproducts-namespace
      namespace: flux-services
