---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-miditf-central-controller
  namespace: flux-services
spec:
  type: kv-v2
  mount: mid-itf
  path: central-controller
  # version: 2
  destination:
    name: vault-miditf-central-controller
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
