---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-miditf-central-controller-no-hw
  namespace: flux-services
spec:
  type: kv-v2
  mount: mid-itf
  path: central-controller-no-hw # HW in the loop? Set "path: central-controller"
  # version: 2
  destination:
    name: vault-miditf-central-controller-no-hw
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
