---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-midaa-kapb
  namespace: flux-services
spec:
  type: kv-v2
  mount: mid-aa
  path: losberg/central-controller
  # version: 2
  destination:
    name: vault-midaa-kapb
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-midaa-cbf
  namespace: flux-services
spec:
  type: kv-v2
  mount: mid-aa
  path: losberg/cbf-overrides
  # version: 2
  destination:
    name: vault-midaa-cbf
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-midaa-global
  namespace: flux-services
spec:
  type: kv-v2
  mount: mid-aa
  path: losberg/global-overrides
  # version: 2
  destination:
    name: vault-midaa-global
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-midaa-sdp
  namespace: flux-services
spec:
  type: kv-v2
  mount: mid-aa
  path: losberg/sdp-overrides
  # version: 2
  destination:
    name: vault-midaa-sdp
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-midaa-tmc
  namespace: flux-services
spec:
  type: kv-v2
  mount: mid-aa
  path: losberg/tmc-overrides
  # version: 2
  destination:
    name: vault-midaa-tmc
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth