---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-midaa-kapb
  namespace: flux-services
spec:
  type: kv-v2
  mount: mid-aa
  path: losberg/central-controller
  # version: 2
  destination:
    name: vault-midaa-kapb
    create: true
  refreshAfter: 300s
  vaultAuthRef: flux-vault-auth