apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cbf-ec-pvc
  namespace: cbf-engineering-console
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: ceph-cephfs
  volumeMode: Filesystem
